### PR TITLE
First version of org switching command.

### LINKED ISSUE #11: Add new operation to switch "organisation" or "context"
It should be possible to switch the default context without having to sign-in again. Currently the context is just the current organisation, but maybe there will be more context eventually? Either way, maybe a "set-context" command is required, a la `kubectl` (but perhaps without it being a sub-command?):

https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration

### PR DESCRIPTION
**Pull request by russmiles**
Signed-off-by: Russ Miles <russ@russmiles.com>

Closes #11

### CODE REVIEW

**Comment by russmiles** [comment]
Nah, lacking a LARGE note @Lawouach ;) On it then I'll merge.

**Comment by Lawouach** [comment]
tx. looks good :)

**Comment by russmiles** [comment]
Once this merge is in @Lawouach I think we're good for a new `0.2.0 release?

**Comment by Lawouach** [comment]
yes :)

**Pull request merged**
